"""Sample Non-Human Identity data.

Mirrors frontend/data/identities.ts so the API returns the same
demo inventory the frontend ships with mock data. In Phase 3+ this
would be replaced by a PostgreSQL-backed repository.
"""

from datetime import datetime, timedelta

from app.models.identity import NonHumanIdentity


def _days_ago(n: int) -> str:
    return (datetime.utcnow() - timedelta(days=n)).strftime("%Y-%m-%d")


_RAW = [
    dict(id="nhi-001", name="aws-prod-lambda-deploy-key", type="API Key", owner=None,
         system="AWS", environment="Production", last_used=3, created=420, rotation=None,
         permission="Admin", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=True, status="Active"),
    dict(id="nhi-002", name="github-actions-release-pat", type="CI/CD Secret", owner=None,
         system="GitHub Actions", environment="Production", last_used=1, created=300, rotation=None,
         permission="Admin", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=True, status="Active"),
    dict(id="nhi-003", name="svc-billing-azure-sp", type="Service Account", owner="Finance Ops Team",
         system="Azure", environment="Staging", last_used=40, created=500, rotation=60,
         permission="Read/Write", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-004", name="jenkins-cicd-deploy-secret", type="CI/CD Secret", owner="DevOps Team",
         system="Jenkins", environment="Production", last_used=10, created=260, rotation=120,
         permission="Admin", has_expiration=False, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-005", name="postgres-analytics-readonly", type="Database Credential", owner="Data Engineering",
         system="PostgreSQL", environment="Production", last_used=2, created=600, rotation=45,
         permission="Read-Only", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-006", name="salesforce-integration-oauth", type="OAuth Token", owner=None,
         system="Salesforce", environment="Production", last_used=200, created=700, rotation=None,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-007", name="servicenow-incident-api-key", type="API Key", owner="IT Service Management",
         system="ServiceNow", environment="Production", last_used=15, created=200, rotation=30,
         permission="Read/Write", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-008", name="k8s-cluster-admin-sa", type="Service Account", owner=None,
         system="Kubernetes", environment="Production", last_used=5, created=365, rotation=400,
         permission="Admin", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-009", name="internal-api-gateway-key", type="API Key", owner="Platform Team",
         system="Internal API", environment="Development", last_used=20, created=150, rotation=20,
         permission="Read/Write", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-010", name="aws-backup-service-role", type="Cloud Access Key", owner="Infra Team",
         system="AWS", environment="Production", last_used=250, created=800, rotation=150,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=False, status="Inactive"),
    dict(id="nhi-011", name="azure-storage-sas-token", type="Cloud Access Key", owner="Storage Team",
         system="Azure", environment="Staging", last_used=8, created=90, rotation=15,
         permission="Read-Only", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-012", name="github-actions-terraform-sa", type="Service Account", owner=None,
         system="GitHub Actions", environment="Production", last_used=12, created=310, rotation=200,
         permission="Admin", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-013", name="jenkins-legacy-ssh-key", type="SSH Key", owner=None,
         system="Jenkins", environment="Production", last_used=220, created=900, rotation=None,
         permission="Admin", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=False, status="Pending Review"),
    dict(id="nhi-014", name="postgres-app-writer", type="Database Credential", owner="Backend Team",
         system="PostgreSQL", environment="Production", last_used=1, created=400, rotation=95,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-015", name="salesforce-marketing-api-key", type="API Key", owner="Marketing Ops",
         system="Salesforce", environment="Production", last_used=60, created=250, rotation=30,
         permission="Read/Write", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-016", name="servicenow-cmdb-sync-account", type="Service Account", owner=None,
         system="ServiceNow", environment="Production", last_used=190, created=600, rotation=130,
         permission="Read/Write", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=False, status="Suspended"),
    dict(id="nhi-017", name="k8s-ci-deployer-cert", type="Machine Certificate", owner="Platform Team",
         system="Kubernetes", environment="Production", last_used=4, created=100, rotation=None,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-018", name="internal-api-partner-oauth", type="OAuth Token", owner="Partnerships Team",
         system="Internal API", environment="Staging", last_used=5, created=120, rotation=10,
         permission="Read-Only", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-019", name="aws-root-automation-key", type="Cloud Access Key", owner=None,
         system="AWS", environment="Production", last_used=300, created=1000, rotation=None,
         permission="Owner", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=True, status="Active"),
    dict(id="nhi-020", name="azure-function-managed-identity", type="Service Account", owner="App Platform Team",
         system="Azure", environment="Development", last_used=3, created=60, rotation=20,
         permission="Read/Write", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-021", name="github-actions-npm-publish-token", type="CI/CD Secret", owner="Frontend Team",
         system="GitHub Actions", environment="Production", last_used=25, created=180, rotation=100,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-022", name="jenkins-shared-build-account", type="Service Account", owner=None,
         system="Jenkins", environment="Production", last_used=45, created=500, rotation=250,
         permission="Admin", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-023", name="postgres-reporting-svc-cred", type="Database Credential", owner="BI Team",
         system="PostgreSQL", environment="Staging", last_used=30, created=200, rotation=40,
         permission="Read-Only", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-024", name="salesforce-sandbox-test-key", type="API Key", owner="QA Team",
         system="Salesforce", environment="Sandbox", last_used=100, created=300, rotation=150,
         permission="Read/Write", has_expiration=False, is_shared=True, has_docs=False,
         secret_exposed=False, status="Inactive"),
    dict(id="nhi-025", name="servicenow-webhook-secret", type="CI/CD Secret", owner=None,
         system="ServiceNow", environment="Production", last_used=210, created=400, rotation=None,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=True, status="Active"),
    dict(id="nhi-026", name="k8s-monitoring-readonly-sa", type="Service Account", owner="SRE Team",
         system="Kubernetes", environment="Production", last_used=6, created=220, rotation=50,
         permission="Read-Only", has_expiration=True, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-027", name="internal-api-billing-db-cred", type="Database Credential", owner="Billing Team",
         system="Internal API", environment="Production", last_used=2, created=350, rotation=110,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
    dict(id="nhi-028", name="aws-dev-sandbox-access-key", type="Cloud Access Key", owner="Sandbox Users",
         system="AWS", environment="Development", last_used=15, created=90, rotation=20,
         permission="Read/Write", has_expiration=True, is_shared=True, has_docs=False,
         secret_exposed=False, status="Active"),
    dict(id="nhi-029", name="azure-ad-app-registration-secret", type="OAuth Token", owner=None,
         system="Azure", environment="Production", last_used=240, created=700, rotation=300,
         permission="Admin", has_expiration=False, is_shared=False, has_docs=False,
         secret_exposed=False, status="Suspended"),
    dict(id="nhi-030", name="jenkins-node-agent-ssh-key", type="SSH Key", owner="Build Infra Team",
         system="Jenkins", environment="Production", last_used=3, created=500, rotation=95,
         permission="Read/Write", has_expiration=False, is_shared=False, has_docs=True,
         secret_exposed=False, status="Active"),
]


def get_sample_identities() -> list[NonHumanIdentity]:
    identities = []
    for row in _RAW:
        identities.append(
            NonHumanIdentity(
                id=row["id"],
                name=row["name"],
                type=row["type"],
                owner=row["owner"],
                system=row["system"],
                environment=row["environment"],
                last_used_date=_days_ago(row["last_used"]),
                created_date=_days_ago(row["created"]),
                days_since_rotation=row["rotation"],
                permission_level=row["permission"],
                has_expiration=row["has_expiration"],
                is_shared=row["is_shared"],
                has_documentation=row["has_docs"],
                secret_exposed=row["secret_exposed"],
                status=row["status"],
            )
        )
    return identities
